<?php

use Illuminate\Database\Seeder;

class ExamReadinessSettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $examReadinessSettings = collect([
            [
                'name' => 'Adobe: Design Graphic Photoshop', 
                'slug' => 'adobe',
                'is_opened_slug' => 'xr_adobe_is_opened',
                'is_opened_slug_value' => '0',
                'student_year_slug' => 'xr_adobe_student_year',
                'student_year_slug_value' => '',
                'ssp_limiter_slug' => 'xr_adobe_ssp',
                'ssp_limiter_slug_value' => '1',
                'department_limiter_slug' => 'xr_adobe_department',
                'department_limiter_slug_value' => [],
            ],
            [
                'name' => 'Android Native (Dicoding)', 
                'slug' => 'native_android',
                'is_opened_slug' => 'xr_native_android_is_opened',
                'is_opened_slug_value' => '1',
                'student_year_slug' => 'xr_native_android_student_year',
                'student_year_slug_value' => '',
                'ssp_limiter_slug' => 'xr_native_android_ssp',
                'ssp_limiter_slug_value' => '1',
                'department_limiter_slug' => 'xr_native_android_department',
                'department_limiter_slug_value' => [],
            ],
            [
                'name' => 'AR (Vaganza)', 
                'slug' => 'ar_vaganza',
                'is_opened_slug' => 'xr_ar_vaganza_is_opened',
                'is_opened_slug_value' => '1',
                'student_year_slug' => 'xr_ar_vaganza_student_year',
                'student_year_slug_value' => '3',
                'ssp_limiter_slug' => 'xr_ar_vaganza_ssp',
                'ssp_limiter_slug_value' => '1',
                'department_limiter_slug' => 'xr_ar_vaganza_department',
                'department_limiter_slug_value' => ['MM'],
            ],
            [
                'name' => 'ACP #1', 
                'slug' => 'acp_1',
                'is_opened_slug' => 'xr_acp_1_is_opened',
                'is_opened_slug_value' => '1',
                'student_year_slug' => 'xr_acp_1_student_year',
                'student_year_slug_value' => '1',
                'ssp_limiter_slug' => 'xr_acp_1_ssp',
                'ssp_limiter_slug_value' => '0',
                'department_limiter_slug' => 'xr_acp_1_department',
                'department_limiter_slug_value' => [],
            ],
            [
                'name' => 'ACP #2', 
                'slug' => 'acp_2',
                'is_opened_slug' => 'xr_acp_2_is_opened',
                'is_opened_slug_value' => '1',
                'student_year_slug' => 'xr_acp_2_student_year',
                'student_year_slug_value' => '1',
                'ssp_limiter_slug' => 'xr_acp_2_ssp',
                'ssp_limiter_slug_value' => '0',
                'department_limiter_slug' => 'xr_acp_2_department',
                'department_limiter_slug_value' => [],
            ],
            [
                'name' => 'ACP #3', 
                'slug' => 'acp_3',
                'is_opened_slug' => 'xr_acp_3_is_opened',
                'is_opened_slug_value' => '1',
                'student_year_slug' => 'xr_acp_3_student_year',
                'student_year_slug_value' => '1',
                'ssp_limiter_slug' => 'xr_acp_3_ssp',
                'ssp_limiter_slug_value' => '0',
                'department_limiter_slug' => 'xr_acp_3_department',
                'department_limiter_slug_value' => [],
            ],
            [
                'name' => 'IoT', 
                'slug' => 'iot',
                'is_opened_slug' => 'xr_iot_is_opened',
                'is_opened_slug_value' => '1',
                'student_year_slug' => 'xr_iot_student_year',
                'student_year_slug_value' => '3',
                'ssp_limiter_slug' => 'xr_iot_ssp',
                'ssp_limiter_slug_value' => '1',
                'department_limiter_slug' => 'xr_iot_department',
                'department_limiter_slug_value' => ['TKJ', 'RPL'],
            ],
            [
                'name' => 'LS', 
                'slug' => 'ls_cable',
                'is_opened_slug' => 'xr_ls_cable_is_opened',
                'is_opened_slug_value' => '1',
                'student_year_slug' => 'xr_ls_cable_student_year',
                'student_year_slug_value' => '2',
                'ssp_limiter_slug' => 'xr_ls_cable_ssp',
                'ssp_limiter_slug_value' => '1',
                'department_limiter_slug' => 'xr_ls_cable_department',
                'department_limiter_slug_value' => ['TKJ', 'RPL', 'MM', 'Telin', 'TAV'],
            ],
            [
                'name' => 'Microsoft: MTA Network Fundamental', 
                'slug' => 'mta_nf',
                'is_opened_slug' => 'xr_mta_nf_is_opened',
                'is_opened_slug_value' => '1',
                'student_year_slug' => 'xr_mta_nf_student_year',
                'student_year_slug_value' => '2',
                'ssp_limiter_slug' => 'xr_mta_nf_ssp',
                'ssp_limiter_slug_value' => '1',
                'department_limiter_slug' => 'xr_mta_nf_department',
                'department_limiter_slug_value' => ['TKJ'],
            ],
            [
                'name' => 'Microsoft: MTA Software Fundamental', 
                'slug' => 'mta_sf',
                'is_opened_slug' => 'xr_mta_sf_is_opened',
                'is_opened_slug_value' => '1',
                'student_year_slug' => 'xr_mta_sf_student_year',
                'student_year_slug_value' => '2',
                'ssp_limiter_slug' => 'xr_mta_sf_ssp',
                'ssp_limiter_slug_value' => '1',
                'department_limiter_slug' => 'xr_mta_sf_department',
                'department_limiter_slug_value' => ['RPL'],
            ],
            [
                'name' => 'MikroTik: MTCNA', 
                'slug' => 'mtcna',
                'is_opened_slug' => 'xr_mtcna_is_opened',
                'is_opened_slug_value' => '1',
                'student_year_slug' => 'xr_mtcna_student_year',
                'student_year_slug_value' => '3',
                'ssp_limiter_slug' => 'xr_mtcna_ssp',
                'ssp_limiter_slug_value' => '1',
                'department_limiter_slug' => 'xr_mtcna_department',
                'department_limiter_slug_value' => ['TKJ'],
            ],
            [
                'name' => 'Axelbit: Network Operators', 
                'slug' => 'network_operator',
                'is_opened_slug' => 'xr_network_operator_is_opened',
                'is_opened_slug_value' => '1',
                'student_year_slug' => 'xr_network_operator_student_year',
                'student_year_slug_value' => '3',
                'ssp_limiter_slug' => 'xr_network_operator_ssp',
                'ssp_limiter_slug_value' => '1',
                'department_limiter_slug' => 'xr_network_operator_department',
                'department_limiter_slug_value' => ['TKJ'],
            ],
            [
                'name' => 'Remidial ACP #1', 
                'slug' => 'remidial_acp_1',
                'is_opened_slug' => 'xr_remidial_axioo_1_is_opened',
                'is_opened_slug_value' => '1',
                'student_year_slug' => 'xr_remidial_axioo_1_student_year',
                'student_year_slug_value' => '1',
                'ssp_limiter_slug' => 'xr_remidial_axioo_1_ssp',
                'ssp_limiter_slug_value' => '0',
                'department_limiter_slug' => 'xr_remidial_axioo_1_department',
                'department_limiter_slug_value' => [],
            ],
            [
                'name' => 'Remidial ACP #2', 
                'slug' => 'remidial_acp_2',
                'is_opened_slug' => 'xr_remidial_axioo_2_is_opened',
                'is_opened_slug_value' => '1',
                'student_year_slug' => 'xr_remidial_axioo_2_student_year',
                'student_year_slug_value' => '1',
                'ssp_limiter_slug' => 'xr_remidial_axioo_2_ssp',
                'ssp_limiter_slug_value' => '0',
                'department_limiter_slug' => 'xr_remidial_axioo_2_department',
                'department_limiter_slug_value' => [],
            ],
            [
                'name' => 'Remidial ACP #3', 
                'slug' => 'remidial_acp_3',
                'is_opened_slug' => 'xr_remidial_axioo_3_is_opened',
                'is_opened_slug_value' => '1',
                'student_year_slug' => 'xr_remidial_axioo_3_student_year',
                'student_year_slug_value' => '1',
                'ssp_limiter_slug' => 'xr_remidial_axioo_3_ssp',
                'ssp_limiter_slug_value' => '0',
                'department_limiter_slug' => 'xr_remidial_axioo_3_department',
                'department_limiter_slug_value' => [],
            ],
            [
                'name' => 'Telview: Surveillance Technology Fundamental (TCPS)', 
                'slug' => 'telview_tcps',
                'is_opened_slug' => 'xr_telview_tcps_is_opened',
                'is_opened_slug_value' => '1',
                'student_year_slug' => 'xr_telview_tcps_student_year',
                'student_year_slug_value' => '3',
                'ssp_limiter_slug' => 'xr_telview_tcps_ssp',
                'ssp_limiter_slug_value' => '1',
                'department_limiter_slug' => 'xr_telview_tcps_department',
                'department_limiter_slug_value' => ['TKJ'],
            ],
            [
                'name' => 'Telview: Surveillance Technology Junior Technician (TCT)',
                'slug' => 'telview_tct',
                'is_opened_slug' => 'xr_telview_tct_is_opened',
                'is_opened_slug_value' => '1',
                'student_year_slug' => 'xr_telview_tct_student_year',
                'student_year_slug_value' => '3',
                'ssp_limiter_slug' => 'xr_telview_tct_ssp',
                'ssp_limiter_slug_value' => '1',
                'department_limiter_slug' => 'xr_telview_tct_department',
                'department_limiter_slug_value' => ['TKJ'],
            ],
        ]);
		setting(['exam_readiness_settings' => $examReadinessSettings->toJson()])->save();
		foreach ($examReadinessSettings as $examReadinessSetting) {
            setting([
                $examReadinessSetting['is_opened_slug'] => $examReadinessSetting['is_opened_slug_value'],
                $examReadinessSetting['student_year_slug'] => $examReadinessSetting['student_year_slug_value'],
                $examReadinessSetting['ssp_limiter_slug'] => $examReadinessSetting['ssp_limiter_slug_value'],
                $examReadinessSetting['department_limiter_slug'] => collect($examReadinessSetting['department_limiter_slug_value'])->toJson(),
            ])->save();
		}
    }
}
